apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: movie-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: movie-app
  template:
    metadata:
      labels:
        app: movie-app
    spec:
      containers:
      - name: movie-app
        image: roop14/multibranch-flask-app:build-5
        ports:
        - containerPort: 5000
