apiVersion: v1
kind: Service
metadata:
  name: movie-app-service      # âœ… REQUIRED
  namespace: movie-app         # OK since you're explicitly using namespace
spec:
  type: LoadBalancer
  selector:
    app: movie-app
  ports:
    - port: 80
      targetPort: 5000